#!/usr/bin/env python3
"""Exports the six deck layouts of the Oric original (oricport/tools/deckgen.py, the generator
the TAP was built from) as C# data for the enhanced remake.

    python3 tools/export_decks.py   ->  src/Quazitronic.Core/Game/DeckData.g.cs

Needs the oricport source tree (git-ignored) and numpy. The output is committed, so a normal
build never needs this script.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "oricport", "tools"))

import deckgen  # noqa: E402

STYLES = ['panel', 'brick']


def main():
    out = []
    out.append("// <auto-generated> by tools/export_decks.py from oricport/tools/deckgen.py - do not edit.")
    out.append("namespace Quazitronic.Game;")
    out.append("")
    out.append("internal static partial class DeckData")
    out.append("{")
    out.append("    // Per deck: tiles (16 x 16, row-major by j, bits 0-1 level, bits 2-4 kind),")
    out.append("    // start tile (the lift), Oric ink colour, void colour and wall style (0 panel, 1 brick).")
    out.append("    private static readonly RawDeck[] Raw =")
    out.append("    {")
    for d in range(len(deckgen.DECKS)):
        seed, W, H, sty, ink, void = deckgen.DECKS[d]
        g, lv, start = deckgen.make_layout(seed, W, H)
        tiles = ((g.astype(int) << 2) | lv).flatten()
        rows = []
        for j in range(H):
            rows.append("            " + ", ".join("0x%02X" % int(t) for t in tiles[j * W:(j + 1) * W]) + ",")
        out.append("        new(%d, %d, %d, %d, %d, new byte[]" % (start[0], start[1], ink, void, STYLES.index(sty)))
        out.append("        {")
        out.extend(rows)
        out.append("        }),")
    out.append("    };")
    out.append("}")
    path = os.path.join(ROOT, "src", "Quazitronic.Core", "Game", "DeckData.g.cs")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", path)


if __name__ == "__main__":
    main()
