#!/usr/bin/env python3
"""Exports the Oric original's graphics data from its generators (oricport/tools/mkgfx.py and
deckgen.py) as C# data for ORIGINAL mode, which redraws the Oric screen natively:

    python3 tools/export_original.py   ->  src/Quazitronic.Core/Original/OriginalData.g.cs

Font, droid / explosion / bullet sprites (pre-shifted data + masks, as the Oric draws them), the
two planar deck charsets, each deck's cell map and left-column fix table, the status panel, the
framed text screen and the logo. Needs the oricport source tree (git-ignored) and numpy; the
output is committed, so a normal build never needs this script.
"""
import base64
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "oricport", "tools"))

import deckgen  # noqa: E402
import mkgfx  # noqa: E402


def b64(data):
    return base64.b64encode(bytes(data)).decode()


def sprite(art, auto_outline=True):
    ink, opq = mkgfx.to_pixels(art)
    ink = np.pad(ink, ((1, 1), (1, 1)))
    opq = np.pad(opq, ((1, 1), (1, 1)))
    if auto_outline:
        opq = mkgfx.outline(opq)
    h, w = ink.shape
    wbytes = (w + max(mkgfx.SHIFTS) + 5) // 6
    phases = []
    for s in mkgfx.SHIFTS:
        d, m = mkgfx.pack(ink, opq, s, wbytes)
        phases.append(bytes(d) + bytes(m))
    return h, wbytes, w // 2, phases


def decks():
    builds = [deckgen.build(d) for d in range(len(deckgen.DECKS))]
    styles = mkgfx.STYLES
    sets = {st: set() for st in styles}
    for d, b in enumerate(builds):
        sets[deckgen.DECKS[d][3]].update(b['cells'])
    orders = {st: sorted(sets[st]) for st in styles}
    csets = []
    for st in styles:
        planes = bytearray(1536)
        for k, c in enumerate(orders[st]):
            for r in range(6):
                planes[r * 256 + k] = c[r]
        csets.append(planes)
    out = []
    for d, b in enumerate(builds):
        st = deckgen.DECKS[d][3]
        idx = {c: k for k, c in enumerate(orders[st])}
        remap = [idx[c] for c in b['cells']]
        cm = np.vectorize(lambda k: remap[k])(b['cellmap']).astype(np.uint8)
        lf = bytearray(256)
        for k, c in enumerate(b['cells']):
            lf[remap[k]] = b['leftfix'][k]
        rows, cols = cm.shape
        out.append(dict(cols=cols, rows=rows, X0=b['X0'], Y0=b['Y0'], ink=b['ink'], void=b['void'],
                        style=styles.index(st), leftfix=lf, cells=cm.flatten().tobytes()))
    return csets, out


def main():
    lines = ["// <auto-generated> by tools/export_original.py from the Oric original's generators - do not edit.",
             "namespace Quazitronic.Original;", "", "internal static partial class OriginalData", "{"]
    lines.append(f'    public static readonly byte[] Font = Unpack("{b64(mkgfx.FONT)}");')
    sprites = [mkgfx.droid_art(i) for i in range(len(mkgfx.CLASSES))]
    lines.append("    // Sprites: the nine droid classes (0 = influence device), then explosion 0, explosion 1 and the bullet.")
    lines.append("    public static readonly SpriteData[] Sprites =")
    lines.append("    {")
    for art, outl in [(a, True) for a in sprites] + [(mkgfx.BOOM0, True), (mkgfx.BOOM1, False), (mkgfx.BULLET, True)]:
        h, w, xo, ph = sprite(art, outl)
        lines.append(f'        new({h}, {w}, {xo}, Unpack("{b64(ph[0])}"), Unpack("{b64(ph[1])}")),')
    lines.append("    };")
    csets, dk = decks()
    lines.append("    public static readonly byte[][] Charsets =")
    lines.append("    {")
    for c in csets:
        lines.append(f'        Unpack("{b64(c)}"),')
    lines.append("    };")
    lines.append("    public static readonly DeckPicture[] Decks =")
    lines.append("    {")
    for d in dk:
        lines.append(f'        new({d["cols"]}, {d["rows"]}, {d["X0"]}, {d["Y0"]}, {d["ink"]}, {d["void"]}, {d["style"]}, '
                     f'Unpack("{b64(d["leftfix"])}"), Unpack("{b64(d["cells"])}")),')
    lines.append("    };")
    panel = bytes(sum(mkgfx.panel_image(), []))
    frame = bytes(sum(mkgfx.frame_image(), []))
    logo = bytes(mkgfx.logo_bytes())
    lines.append(f'    public static readonly byte[] Panel = Unpack("{b64(panel)}");')
    lines.append(f'    public static readonly byte[] Frame = Unpack("{b64(frame)}");')
    lines.append(f'    public static readonly byte[] Logo = Unpack("{b64(logo)}");')
    lines.append("}")
    path = os.path.join(ROOT, "src", "Quazitronic.Core", "Original", "OriginalData.g.cs")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", path, os.path.getsize(path) // 1024, "KB;", "panel", len(panel), "frame", len(frame), "logo", len(logo))


if __name__ == "__main__":
    main()
